import { StyleSheet,Dimensions } from "react-native";
export default StyleSheet.create({
    container:{
        flex:1
    },
    header:{
        padding:10,
    },
    job_title:{
        fontSize:30,
        fontWeight:"bold",
        color:"#546e7a"
    },
    locations:{
        marginVertical:10,
        fontSize:20,
        fontWeight:"bold",
        color:"#ef5350"
    },
    level:{
        fontSize:20,
        fontWeight:"bold",
        color:"#ef5350"
    },
    job_detail:{
        marginTop:10,
        textAlign:"center",
        fontSize:25,
        fontWeight:"bold",
        color:"#546e7a"
    },
    body:{
        flex:1,
        backgroundColor:"white",
    },
    content:{
        margin:10,
        fontSize:20,
    },
    btn_container:{
        flexDirection:"row",
    }

})